# static/admin/config.yml

backend:
  name: git-gateway
  branch: main # 你的主分支名

media_folder: "static/images/uploads" # 上传的图片存放在这里
public_folder: "/images/uploads" # 在文章中引用图片的路径

collections:
  - name: "post" # 集合的唯一标识
    label: "文章" # 在 CMS 界面中显示的名称
    folder: "content/posts" # 对应 Hugo 的内容文件夹
    create: true # 允许在 CMS 中创建新文件
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # 文件名的格式
    fields: # 定义了你在 CMS 编辑器中看到的字段
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "是否草稿", name: "draft", widget: "boolean", default: true}
      - {label: "正文", name: "body", widget: "markdown"}
